from __future__ import annotations

import logging
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from itertools import groupby

from .config import Config
from .sources.base import Opportunity

logger = logging.getLogger(__name__)

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587


def send_digest(
    opportunities: list[tuple[Opportunity, int]],
    config: Config,
) -> None:
    if not config.gmail_app_password:
        logger.warning("No GMAIL_APP_PASSWORD set, skipping email")
        return
    if not config.sender_email or not config.recipient_email:
        logger.warning("Missing email addresses, skipping email")
        return

    subject = (
        f"Fellowship Digest: {len(opportunities)} new opportunities "
        f"({date.today().strftime('%b %d, %Y')})"
    )

    html = _build_html(opportunities)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = config.sender_email
    msg["To"] = config.recipient_email
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(config.sender_email, config.gmail_app_password)
            server.sendmail(config.sender_email, config.recipient_email, msg.as_string())
        logger.info("Email sent to %s with %d opportunities", config.recipient_email, len(opportunities))
    except Exception:
        logger.exception("Failed to send email")


def _build_html(opportunities: list[tuple[Opportunity, int]]) -> str:
    parts = [
        "<html><body>",
        "<h1 style='color:#1a365d;font-family:sans-serif;'>",
        f"Weekly Funding Digest &mdash; {date.today().strftime('%B %d, %Y')}",
        "</h1>",
        f"<p style='font-family:sans-serif;color:#555;'>{len(opportunities)} new opportunities found.</p>",
    ]

    grouped = groupby(
        sorted(opportunities, key=lambda x: x[0].source),
        key=lambda x: x[0].source,
    )

    for source_name, group in grouped:
        items = list(group)
        parts.append(
            f"<h2 style='color:#2c5282;font-family:sans-serif;border-bottom:1px solid #e2e8f0;padding-bottom:4px;'>"
            f"{source_name} ({len(items)})</h2>"
        )

        for opp, score in items:
            deadline_str = opp.deadline.strftime("%b %d, %Y") if opp.deadline else "No deadline listed"
            desc_excerpt = opp.description[:200] + "..." if len(opp.description) > 200 else opp.description

            parts.append(
                "<div style='margin-bottom:16px;padding:12px;border:1px solid #e2e8f0;border-radius:6px;font-family:sans-serif;'>"
                f"<div style='font-size:16px;font-weight:bold;'>"
                f"<a href='{opp.url}' style='color:#2b6cb0;text-decoration:none;'>{opp.title}</a>"
                f"<span style='color:#718096;font-size:12px;font-weight:normal;margin-left:8px;'>Score: {score}</span>"
                "</div>"
                f"<div style='font-size:13px;color:#555;margin-top:4px;'>"
                f"<strong>Deadline:</strong> {deadline_str}"
            )

            if opp.amount:
                parts.append(f" &bull; <strong>Amount:</strong> {opp.amount}")
            if opp.organization:
                parts.append(f" &bull; <strong>Org:</strong> {opp.organization}")

            parts.append("</div>")

            if desc_excerpt:
                parts.append(
                    f"<div style='font-size:13px;color:#666;margin-top:6px;'>{desc_excerpt}</div>"
                )

            parts.append("</div>")

    parts.append(
        "<hr style='border:none;border-top:1px solid #e2e8f0;margin-top:24px;'>"
        "<p style='font-family:sans-serif;font-size:12px;color:#999;'>"
        "Generated by fellowship-funding search. "
        "Relevance scores are based on keyword matching and may not reflect actual fit."
        "</p>"
        "</body></html>"
    )

    return "\n".join(parts)
